dictionaryDefinitions:
  - name: project-words
    path: "./.cspell.project-words.txt"
    addWords: true
dictionaries:
  - project-words
ignorePaths:
  - "./.cspell.project-words.txt"
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - Email
      - "/^\\s*```[\\s\\S]*?^\\s*```/gm"
      - "\\[[^\\]]*\\]\\(mailto:[^\\)]*\\)"
